function robCRSgripper( robot, power )
%ROBCRSGRIPPER  CRS gripper with analog sensor.
%
%   robCRSripper( robot, power )
%
%   Gripper usable with CRS robots.
%
%   Input:
%     robot .. robot control structure.
%     power .. gripper value in range <-1;1>, sets position or power:
%                 .. absolute value up to 0.1 sets gripper
%                    to a given position with small force
%                    (-0.1 .. full open, 0.1 .. full close).
%                 .. absolute value greater than 0.1 sets opening (-) or
%                     closing (+) force up to maximal force (+/- 1).

% (c) 2009-05, Pavel Krsek
% (c) 2010-02-15, Martin Matousek
% Last change: $Date:: 2010-02-17 17:51:32 +0100 #$
%              $Revision: 2 $

% robot.gripper_bounds ... position range, [ open closed ]
if( power < -1 || power > 1 )
  error( 'Gripper value out of bounds.' );
end

b = robot.gripper_bounds;
f = robot.gripper_bounds_force;
if( abs( power ) <= 0.1 )  % 'position' mode
  pos = ( ( 0.1 - power ) * b(1) + ( power - 0.1 ) * b(2)+ 0.1 ) / 0.2;
else % 'force' mode

  % the force is simulated such that we set the position otside
  % the physical range and the force is generated by P component of 
  % PID regulator (the I component must be definitely set to 0!)

  if( power > 0 ) % set pos between b(2) and f(2)
    pos = ( ( 1 - power ) * b(2) + ( power - 0.1 ) * f(2) ) / 0.9;
  else % set pos between b(1) and f(1)
    power = -power;
    pos = ( ( 1 - power ) * b(1) + ( power - 0.1 ) * f(1) ) / 0.9;
  end
end;

% Release errors and reset controller
robot.com.writeline( [ 'RELEASE' robot.gripper_ax ':' ] );

% Set position on gripper
robot.com.writeline( [ 'G' robot.gripper_ax ':' num2str( pos ) ] );

% Release motor of open gripper
if( power == 0 )
  bbwaitforgrip( robot ); %, pos );
  robot.com.writeline( [ 'RELEASE' robot.gripper_ax ':'] ); 
end
